# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

#exec-once = waybar
# exec-once = nm-applet &
#exec-once = waybar & hyprpaper & hyprctl setcursor adwaita 24 & steam -silent
exec-once = waybar & ~/.config/hypr/randomwallpaper.sh & hyprctl setcursor Bibata-Modern-Classic 24
exec-once = nwg-wrapper -t ~/.config/nwg-wrapper/bindings.pango -c ~/.config/nwg-wrapper/bindings.css -o HDMI-A-1 -p right -ml 20 -mt 20 -l 1 -si

exec-once = hypridle
exec-once = hyprsunset
