# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = match:class .*, float on, size 960 540, center on
windowrule = match:class .*, suppress_event maximize # You'll probably like this.
